services:
  - type: web
    name: haven-ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -b 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false